name: Create Release Version & Publish Package

on:
  push:
    branches: [dbo-test]

jobs:
  dbo_upload_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifact
        id: release-artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # version: tags/${{ github.event.inputs.version }}
          regex: true
          file: multiverse-core-(.*)\.jar
          target: 'subdir/'

      - name: Upload to dev.bukkit.org
        uses: benwoo1110/dbo-upload-action@main
        with:
          api_token: ${{ secrets.DBO_UPLOAD_API_TOKEN }}
          project_id: 30765
          changelog: ${{ steps.release-artifact.outputs.body }}
          changelog_type: markdown
          display_name: ${{ steps.release-artifact.outputs.version }}
          game_versions: 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.18.1, 1.18.2, 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1
          project_relations: '[{"slug": "multiverse-portals", "type": "optionalDependency"}, {"slug": "multiverse-netherportals", "type": "optionalDependency"}, {"slug": "multiverse-signportals", "type": "optionalDependency"}, {"slug": "multiverse-inventories", "type": "optionalDependency"}]'
          file_path: ${{ github.workspace }}/subdir/multiverse-core-${{ steps.release-artifact.outputs.version }}.jar
          debug: true
